export const PRICING_PLANS = [
    {
        name: "FREE PLAN",
        price: "₹0",
        period: "/ month",
        description: "Perfect for individuals and small businesses.",
        features: [
            "AI invoice generator",
            "Invoice templates",
            "Download as PDF",
            "Save customer details",
            "Product library (basic)",
            "30 invoices per month",
            "Email support",
        ],
        active: true,
        buttonText: "Get Started Free",
    },
    {
        name: "PRO",
        price: "₹299",
        period: "/ month",
        description: "Coming Soon",
        features: [
            "Unlimited invoices",
            "Multi-business profiles",
            "Custom branding (logo + colors)",
            "Advanced templates",
            "Export to Excel",
            "Priority support",
        ],
        active: false,
        buttonText: "Coming Soon",
    },
    {
        name: "ENTERPRISE",
        price: "Custom",
        period: "",
        description: "Coming Soon",
        features: [
            "Team access",
            "Role-based permissions",
            "API access",
            "Automated invoice workflows",
            "Dedicated account manager",
        ],
        active: false,
        buttonText: "Contact Sales",
    },
];
